Bulbizarre	Bulbasaur	
Rondoudou	Jigglypuff
Herbizarre	Ivysaur
Grodoudou	Wigglytuff
Florizarre	Venusaur	
Nosferapti	Zubat
Salamèche	Charmander	
Nosferalto	Golbat
Reptincel	Charmeleon	
Mystherbe	Oddish
Dracaufeu	Charizard	
Ortide	Gloom
Carapuce	Squirtle	
Rafflésia	Vileplume
Carabaffe	Wartortle	
Paras	Paras
Tortank	Blastoise	
Parasect	Parasect
Chenipan	Caterpie	
Mimitoss	Venonat
Chrysacier	Metapod	
Aéromite	Venomoth
Papilusion	Butterfree	
Taupiqueur	Diglett
Aspicot	Weedle	
Triopikeur	Dugtrio
Coconfort	Kakuna	
Miaouss	Meowth
Dardargnan	Beedrill	
Persian	Persian
Roucool	Pidgey	
Psykokwak	Psyduck
Roucoups	Pidgeotto	
Akwakwak	Golduck
Roucarnage	Pigeot	
Férosinge	Mankey
Rattata	Rattata	
Colossinge	Primeape
Rattatac	Raticate	
Caninos	Growlithe
Piafabec	Spearow	
Arcanin	Arcanine
Rapasdepic	Fearow	
Ptitard	Poliwag
Abo	Ekans	
Têtarte	Poliwhirl
Arbok	Arbok	
Tartard	Poliwrath
Pikachu	Pikachu	
Abra	Abra
Raichu	Raichu	
Kadabra	Kadabra
Sabelette	Sandshrew	
Alakazam	Alakazam
Sablaireau	Sandslash	
Machoc	Machoc
Nidoran	Nidoran	
Machopeur	Machoke
Nidorina	Nidorina	
Mackogneur	Machamp
Nidoqueen	Nidoqueen	
Chétiflor	Bellsprout
Nidoran♂	Nidoran ♂	
Boustiflor	Weepinbell
Nidorino	Nidorino	
Empiflor	Victreebel
Nidoking	Nidoking	
Tentacool	Tentacool
Mélofée	Clefairy	
Tentacruel	Tentacruel
Mélodelfe	Clefable	
Racaillou	Geodude
Goupix	Vulpix	
Gravalanch	Graveler
Feunard	Ninetales	
Grolem	Golem
Ponyta	Ponyta	
Kangourex	Kangaskhan
Galopa	Rapidash	
Hypotrempe	Horsea
Ramoloss	Slowpoke	
Hypocéan	Seadra
Flagadoss	Slowbro	
Poissirène	Goldeen
Magnéti	Magnemite	
Poissoroy	Seaking
Magnéton	Magneton	
Stari	Staryu
Canarticho	Farfetch’d	
Staross	Starmie
Doduo	Doduo
M.Mime	Mr.Mime
Dodrio	Dodrio	
Insécateur	Scyther
Otaria	Seel	
Lippoutou	Jynx
Lamantine	Dewgong	
Élektek	Electabuzz
Tadmorv	Grimer	
Magmar	Magmar
Grotadmorv	Mulk	
Scarabrute	Pinsir
Kokiyas	Shellder	
Tauros	Tauros
Crustabri	Cloyster	
Magicaroe	Magikarp
Fantominus	Gastly	
Léviator	Gyarados
Spectrum	Hunter	
Lokhlass	Lapras
Extoplasma	Gengar	
Métamorph	Ditto
Onix	Onix	
Évoli	Eevee
Soporifik	Steelix	
Aquali	Vaporeon
Hypnomade	Hypno	
Voltali	Jolteon
Krabby	Krabby	
Pyroli	Flareon
Krabboss	Kingler	
Porygon	Porygon
Voltorbe	Voltorb	
Amonita	Omanyte
Électrode	Electrode	
Amonistar	Omastar
Nœunœuf	Exeggcute	
Kabuto	Kabuto
Noadkoko	Exeggutor	
Kabutops	Kabutops
Osselait	Cubone	
Ptéra	Aerodactyl
Ossatueur	Marowak	
Ronflex	Snorlax
Kicklee	Hitmonlee	
Artikodin	Articuno
Tygnon	Hitmonchan	
Électhor	Zapdos
Excelangue	Lickitung	
Sulfura	Moltres
Smogo	Koffing	
Minidraco	Dratini
Smogogo	Weezing	
Draco	Dragonair
Rhinocorne	Rhyhorn	
Dracolosse	Dragonite
Rhinoféros	Rhydon	
Mewtwo	Mewtwo
Leveinard	Chansey	
Mew	Mew